#!/usr/bin/env bash
set -euo pipefail

# Dumps real stored jsonb documents from the local dev database into redacted
# fixture files, before any rename touches the code that produced them
# (STD-06). Source of truth for db/user names is the running container, never
# a local settings file. Container: pipe-postgres.

RAIZ="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FIXTURES="$RAIZ/apps/api/tests/fixtures/jsonb"
REDIGIR="$RAIZ/tools/std/redacao.ts"
mkdir -p "$FIXTURES"

read -r DB_NAME DB_USER <<<"$(docker exec pipe-postgres sh -c 'echo $POSTGRES_DB $POSTGRES_USER')"

psql_json() {
  # $1 = sql query producing exactly one row/column with the jsonb array text.
  docker exec pipe-postgres sh -c "psql -U \"$DB_USER\" -d \"$DB_NAME\" -At -c \"$1\""
}

# $1 = table, $2 = jsonb_build_object(...) expression (must alias nothing; bare expr),
# $3 = where clause (no leading 'where'), $4 = timestamp column for "most recent" (empty = skip),
# $5 = output file name under fixtures/.
dump() {
  local table="$1" expr="$2" where="$3" timecol="$4" outfile="$5"
  local sql
  if [ -n "$timecol" ]; then
    sql="with maiores as (select ($expr) as doc from $table where $where order by length(($expr)::text) desc limit 3), recentes as (select ($expr) as doc from $table where $where order by $timecol desc limit 2) select coalesce(jsonb_agg(doc), '[]'::jsonb) from (select doc from maiores union select doc from recentes) t;"
  else
    sql="with maiores as (select ($expr) as doc from $table where $where order by length(($expr)::text) desc limit 5) select coalesce(jsonb_agg(doc), '[]'::jsonb) from maiores;"
  fi
  psql_json "$sql" | node "$REDIGIR" >"$FIXTURES/$outfile"
  echo "wrote $outfile"
}

# --- flow version group ---
dump fluxo_versao \
  "jsonb_build_object('id', id, 'value', global)" \
  "global is not null and global <> '{}'::jsonb" \
  criado_em \
  flow-version-global.json

dump bloco \
  "jsonb_build_object('id', id, 'value', conteudo)" \
  "conteudo <> '{}'::jsonb" \
  "" \
  flow-block-content.json

dump bloco \
  "jsonb_build_object('id', id, 'value', posicao)" \
  "posicao <> '{}'::jsonb" \
  "" \
  flow-block-position.json

dump transicao \
  "jsonb_build_object('id', id, 'value', condicao)" \
  "condicao <> '{}'::jsonb" \
  "" \
  flow-transition-condition.json

# --- flow execution group ---
dump execucao_fluxo \
  "jsonb_build_object('id', id, 'value', contexto)" \
  "contexto <> '{}'::jsonb" \
  iniciada_em \
  flow-execution-context.json

dump execucao_passo \
  "jsonb_build_object('id', id, 'value', entrada)" \
  "entrada is not null" \
  em \
  flow-step-input.json

dump execucao_passo \
  "jsonb_build_object('id', id, 'value', saida)" \
  "saida is not null" \
  em \
  flow-step-output.json

# posicao_no_roteador and process_http_execucao have 0 rows locally today
# (see .planning/.../std/reports/baseline-jsonb-keys.json notes) — those
# fixtures are produced by tools/std/gerar-fixtures-jsonb.ts instead, which
# exercises the real write path in a throwaway tenant, cleaned up after.

# --- outbox group ---
# mensagem.dados and entrega_webhook.payload have 0 non-empty rows locally
# today; also generated by gerar-fixtures-jsonb.ts.

# --- audit group ---
dump log_auditoria \
  "jsonb_build_object('id', id, 'antes', antes, 'depois', depois)" \
  "antes is not null or depois is not null" \
  em \
  audit-before-after.json

# --- crm group ---
# conta.atributos and contato.atributos have 0 non-empty rows locally today
# (no tenant has set either yet); handled by gerar-fixtures-jsonb.ts.

dump lead \
  "jsonb_build_object('id', id, 'value', utm)" \
  "utm <> '{}'::jsonb" \
  criado_em \
  crm-lead-utm.json

dump lead \
  "jsonb_build_object('id', id, 'value', customizados)" \
  "customizados <> '{}'::jsonb" \
  criado_em \
  crm-lead-custom-fields.json

# --- template group ---
dump template_mensagem \
  "jsonb_build_object('id', id, 'value', variaveis)" \
  "variaveis <> '[]'::jsonb" \
  criado_em \
  template-variables.json

echo "done: local-db fixtures written to $FIXTURES"
