/**
 * The reference's "Biblioteca de variáveis" system tab (`$ctrl.openVarLib()`, `BuilderVariablesLibrary`,
 * `VariablesService.getDefaultVariables()`): the fixed catalog of variable names Blip's Builder always
 * offers, independent of the flow being edited.
 *
 * Names and descriptions are catalog data, not an asset (D-33 only bars icons/sounds/images/code): the
 * 113 unconditional entries (`xk.Ay`) plus the 5 flag-gated ones Blip shows once
 * `showTaxDocumentVariable`/`showNewBsuidVariable` are on (`xk.hL`, `xk.WO` — the account this catalog was
 * captured against has both on, matching the 118-row list measured live), sorted the same way the source
 * sorts them (`localeCompare`). `suportada` marks the ones the Pipe engine actually fills: the variable's
 * source must be in `FONTES_SUPORTADAS` (`@pipe/core/flow/context.ts`), and — for `input.*` — the specific
 * property must be one `inboundProvider` (`context.ts`) has a branch for; `input.contentAssistant.*` and
 * `input.message.pp(identity)` are unreached code paths there, so they're marked unsupported like any
 * source with no provider at all. `tunnel.*` counts as supported although it only has a value in a
 * router service, the same condition Blip states in its descriptions.
 */

export interface SystemVariable {
  nome: string;
  descricao: string;
  /** Whether the Pipe engine's variable providers (`@pipe/core/flow/context.ts`) fill this variable. */
  suportada: boolean;
}

export const BLIP_SYSTEM_VARIABLES: readonly SystemVariable[] = [
  { nome: 'agent.email', descricao: 'O e-mail do atendente (visível apenas em respostas prontas no Desk).', suportada: false },
  { nome: 'agent.firstName', descricao: 'O primeiro nome do atendente (visível apenas em respostas prontas no Desk).', suportada: false },
  { nome: 'agent.fullName', descricao: 'O nome completo do atendente (visível apenas em respostas prontas no Desk).', suportada: false },
  { nome: 'agent.identity', descricao: 'A identidade do agente no formato name@domain. (Visível apenas em respostas prontas no Desk)', suportada: false },
  { nome: 'agent.phoneNumber', descricao: 'O número de telefone do agente. (Visível apenas em respostas prontas no Desk)', suportada: false },
  { nome: 'aiAgent.agentResponse', descricao: 'Lista de respostas geradas pela IA', suportada: false },
  { nome: 'aiAgent.errorCode', descricao: 'Código do erro que causou o redirecionamento', suportada: false },
  { nome: 'aiAgent.message', descricao: 'O envelope de mensagem enviado pela IA', suportada: false },
  { nome: 'aiAgent.name', descricao: 'Nome da action cadastrada', suportada: false },
  { nome: 'aiAgent.parameters', descricao: 'Parâmetros enviados pela IA cadastrados na Action', suportada: false },
  { nome: 'aiAgent.redirect', descricao: 'Indica o tipo de redirecionamento', suportada: false },
  { nome: 'aiAgent.skill_id', descricao: 'Identificador da habilidade (skill) associada à mensagem executada', suportada: false },
  { nome: 'aiAgent.skillName', descricao: 'Nome da habilidade associada à mensagem', suportada: false },
  { nome: 'aiAgent.task_id', descricao: 'Identificador da tarefa associada à mensagem executada', suportada: false },
  { nome: 'aiAgent.taskName', descricao: 'Nome da tarefa associada à mensagem', suportada: false },
  { nome: 'aiAgent.toolCall_id', descricao: 'Identificador da tool call solicitada para ser executada pela IA', suportada: false },
  { nome: 'aiAgent.userMessage', descricao: 'Mensagem original do usuário', suportada: false },
  { nome: 'aiAgent.userMessage_id', descricao: 'Identificador único da mensagem do usuário', suportada: false },
  { nome: 'aiAnswers.response', descricao: 'Resposta à chamada da API de IA', suportada: false },
  { nome: 'aiAnswers.statusCode', descricao: 'Código status de resposta http do retorno da chamada a API', suportada: false },
  { nome: 'application.domain', descricao: "O domínio no qual a aplicação do bot está executando (normalmente 'msging.net')", suportada: true },
  { nome: 'application.identifier', descricao: 'O identificador único da aplicação do bot', suportada: true },
  { nome: 'application.identity', descricao: "A identidade da aplicação do bot (igual a 'identifier@domain')", suportada: true },
  { nome: 'application.instance', descricao: 'A instância do nodo da aplicação do bot', suportada: true },
  { nome: 'application.node', descricao: "O nodo da aplicação do bot (igual a 'identifier@domain/instance')", suportada: true },
  { nome: 'bucket.?', descricao: "Documento armazenado no bucket do bot, onde '?' deve ser substituído pelo ID do documento salvo no bucket", suportada: true },
  { nome: 'calendar.date', descricao: 'Data atual GMT-0 (no formato yyyy-MM-dd)', suportada: true },
  { nome: 'calendar.datetime', descricao: 'Data e hora atual GMT-0 (no formato yyyy-MM-ddTHH:mm:ssZ)', suportada: true },
  { nome: 'calendar.day', descricao: 'Valor que representa o dia no mês corrente', suportada: true },
  { nome: 'calendar.dayOfWeek', descricao: 'Valor que representa o dia da semana do dia corrente. (Em inglês)', suportada: true },
  { nome: 'calendar.hour', descricao: 'Valor que representa a hora corrente', suportada: true },
  { nome: 'calendar.minute', descricao: 'Valor que representa o minuto corrente', suportada: true },
  { nome: 'calendar.month', descricao: 'Valor que representa o mês corrente. ', suportada: true },
  { nome: 'calendar.second', descricao: 'Valor que representa o segundo corrente', suportada: true },
  { nome: 'calendar.time', descricao: 'Hora atual GMT-0 (no formato HH:mm)', suportada: true },
  { nome: 'calendar.tomorrow.date', descricao: 'Data de amanhã GMT-0 (no formato yyyy-MM-dd)', suportada: true },
  { nome: 'calendar.tomorrow.datetime', descricao: 'Data de amanhã e hora atual GMT-0 (no formato yyyy-MM-ddTHH:mm:ssZ)', suportada: true },
  { nome: 'calendar.tomorrow.day', descricao: 'Valor que representa o dia de amanhã no mês corrente.', suportada: true },
  { nome: 'calendar.tomorrow.dayOfWeek', descricao: 'Valor que representa o dia da semana da data de amanhã. (Em inglês)', suportada: true },
  { nome: 'calendar.tomorrow.hour', descricao: 'Valor que representa a hora corrente na data de amanhã.', suportada: true },
  { nome: 'calendar.tomorrow.minute', descricao: 'Valor que representa o minuto corrente na data de amanhã.', suportada: true },
  { nome: 'calendar.tomorrow.month', descricao: 'Valor que representa o mês da data amanhã.', suportada: true },
  { nome: 'calendar.tomorrow.second', descricao: 'Valor que representa o segundo corrente na data de amanhã.', suportada: true },
  { nome: 'calendar.tomorrow.time', descricao: 'Hora atual na data de amanhã GMT-0 (no formato HH:mm)', suportada: true },
  { nome: 'calendar.tomorrow.unixTime', descricao: 'Data de amanhã no formato unix timestamp', suportada: true },
  { nome: 'calendar.tomorrow.unixTimeMilliseconds', descricao: 'Data de amanhã no formato unix timestamp (milisegundos)', suportada: true },
  { nome: 'calendar.tomorrow.year', descricao: 'Valor que representa o ano da data amanhã.', suportada: true },
  { nome: 'calendar.unixTime', descricao: 'Data atual no formato unix timestamp', suportada: true },
  { nome: 'calendar.unixTimeMilliseconds', descricao: 'Data atual no formato unix timestamp (milisegundos)', suportada: true },
  { nome: 'calendar.year', descricao: 'Valor que representa o ano corrente', suportada: true },
  { nome: 'calendar.yesterday.date', descricao: 'Data de ontem GMT-0 (no formato yyyy-MM-dd)', suportada: true },
  { nome: 'calendar.yesterday.datetime', descricao: 'Data de ontem e hora atual GMT-0 (no formato yyyy-MM-ddTHH:mm:ssZ)', suportada: true },
  { nome: 'calendar.yesterday.day', descricao: 'Valor que representa o dia de ontem no mês corrente.', suportada: true },
  { nome: 'calendar.yesterday.dayOfWeek', descricao: 'Valor que representa o dia da semana da data de ontem. (Em inglês)', suportada: true },
  { nome: 'calendar.yesterday.hour', descricao: 'Valor que representa a hora corrente na data de ontem.', suportada: true },
  { nome: 'calendar.yesterday.minute', descricao: 'Valor que representa o minuto corrente na data de ontem.', suportada: true },
  { nome: 'calendar.yesterday.month', descricao: 'Valor que representa o mês da data ontem.', suportada: true },
  { nome: 'calendar.yesterday.second', descricao: 'Valor que representa o segundo corrente na data de ontem.', suportada: true },
  { nome: 'calendar.yesterday.time', descricao: 'Hora atual na data de ontem GMT-0 (no formato HH:mm)', suportada: true },
  { nome: 'calendar.yesterday.unixTime', descricao: 'Data de ontem no formato unix timestamp', suportada: true },
  { nome: 'calendar.yesterday.unixTimeMilliseconds', descricao: 'Data de ontem no formato unix timestamp (milisegundos)', suportada: true },
  { nome: 'calendar.yesterday.year', descricao: 'Valor que representa o ano da data ontem.', suportada: true },
  { nome: 'config.?', descricao: "Variáveis globais definidas na configuração do fluxo onde '?' deve ser substituido pelo valor da variável global criada", suportada: true },
  { nome: 'contact.address', descricao: 'O endereço do contato', suportada: true },
  { nome: 'contact.cellPhoneNumber', descricao: 'O telefone celular do contato', suportada: true },
  { nome: 'contact.city', descricao: 'A cidade do contato.', suportada: true },
  { nome: 'contact.culture', descricao: 'A informação da cultura do usuário (no formato IETF)', suportada: true },
  { nome: 'contact.email', descricao: 'O e-mail do contato.', suportada: true },
  { nome: 'contact.extras.?', descricao: 'Um JSON genérico para armazenar pares de strings (chaves e valor)', suportada: true },
  { nome: 'contact.gender', descricao: 'O sexo do contato', suportada: true },
  { nome: 'contact.group', descricao: 'Indica o nome do grupo ao qual o usuário pertence', suportada: true },
  { nome: 'contact.identity', descricao: 'A identidade do contato no formato name@domain', suportada: true },
  { nome: 'contact.name', descricao: 'O nome do contato', suportada: true },
  { nome: 'contact.phoneNumber', descricao: 'O telefone do contato', suportada: true },
  { nome: 'contact.photoUri', descricao: 'A URI da foto pública do contato', suportada: true },
  { nome: 'contact.serialized', descricao: 'O contato completo no formato JSON', suportada: true },
  { nome: 'contact.source', descricao: 'O nome do canal do contato', suportada: true },
  { nome: 'contact.taxDocument', descricao: 'O documento do contato', suportada: true },
  { nome: 'contact.timezone', descricao: 'O timezone do contato relativo ao GMT', suportada: true },
  { nome: 'contact.whatsAppBsuId', descricao: 'O identificador único do contato na Meta (Business Scoped User ID)', suportada: true },
  { nome: 'contact.whatsAppParentId', descricao: 'O identificador que vincula o contato a um mesmo grupo de empresas na Meta', suportada: true },
  { nome: 'contact.whatsAppUserName', descricao: 'O identificador escolhido pelo usuário do contato na Meta', suportada: true },
  { nome: 'contact.whatsAppWaId', descricao: 'O número de telefone do contato na Meta (ID do WhatsApp)', suportada: true },
  { nome: 'context.?', descricao: "Variáveis de contexto do bot, onde '?' deve ser substituído pelo nome da variável de contexto criada", suportada: true },
  { nome: 'input.content', descricao: 'Conteúdo da mensagem enviado pelo usuário', suportada: true },
  { nome: 'input.contentAssistant.id', descricao: 'Identificador do conteúdo cuja combinação foi reconhecida', suportada: false },
  { nome: 'input.contentAssistant.name', descricao: 'Nome do conteúdo cuja combinação foi reconhecida', suportada: false },
  { nome: 'input.contentAssistant.result', descricao: 'Resposta atrelada à combinação reconhecida', suportada: false },
  { nome: 'input.entity.?.id', descricao: 'Identificador da entidade reconhecida (onde ? deve ser trocado pelo nome da entidade)', suportada: true },
  { nome: 'input.entity.?.name', descricao: 'Nome da entidade reconhecida (onde ? deve ser trocado pelo nome da entidade)', suportada: true },
  { nome: 'input.entity.?.value', descricao: 'Valor da entidade reconhecida (onde ? deve ser trocado pelo nome da entidade)', suportada: true },
  { nome: 'input.intent.answer', descricao: 'Uma das respostas atreladas a intenção reconhecida', suportada: true },
  { nome: 'input.intent.id', descricao: 'Identificador da intenção reconhecida', suportada: true },
  { nome: 'input.intent.name', descricao: 'Nome da intenção reconhecida', suportada: true },
  { nome: 'input.intent.score', descricao: 'Confiabilidade atrelada a intenção reconhecida', suportada: true },
  { nome: 'input.length', descricao: 'Quantidade de conteúdos existente na mensagem enviada pelo usuário (apenas para Collections)', suportada: true },
  { nome: 'input.message', descricao: 'O envelope de mensagem recebido pelo bot', suportada: true },
  { nome: 'input.message.from', descricao: 'O nodo do originador da mensagem recebida', suportada: true },
  { nome: 'input.message.fromidentity', descricao: 'A identidade do originador da mensagem recebida', suportada: true },
  { nome: 'input.message.id', descricao: 'O id da mensagem recebida', suportada: true },
  { nome: 'input.message.pp', descricao: 'O nodo do originador da mensagem recebida, em caso de mensagens delegadas', suportada: false },
  { nome: 'input.message.ppidentity', descricao: 'A identidade do originador da mensagem recebida, em caso de mensagens delegadas', suportada: false },
  { nome: 'input.message.to', descricao: 'O nodo do destinatário da mensagem recebida (normalmente o nodo da aplicação do bot)', suportada: true },
  { nome: 'input.message.toidentity', descricao: 'A identidade do destinatário da mensagem recebida (normalmente a identidade da aplicação do bot)', suportada: true },
  { nome: 'input.type', descricao: 'Tipo da mensagem enviado pelo usuário', suportada: true },
  { nome: 'random.guid', descricao: 'Identificador alfa númerico único', suportada: true },
  { nome: 'random.integer', descricao: 'Número inteiro aleatório', suportada: true },
  { nome: 'random.string', descricao: 'Conjunto de caracteres (string) aleatório', suportada: true },
  { nome: 'resource.?', descricao: "Recurso do bot, onde '?' é a chave do recurso", suportada: true },
  { nome: 'secret.?', descricao: 'Variaveis sensíveis. Atualmente disponível para uso apenas em ações HTTP.', suportada: true },
  { nome: 'state.id', descricao: 'Id do bloco corrente no fluxo', suportada: true },
  { nome: 'state.name', descricao: 'Nome do bloco corrente no fluxo', suportada: true },
  { nome: 'state.previous.id', descricao: 'Id do bloco anterior no fluxo', suportada: true },
  { nome: 'state.previous.name', descricao: 'Nome do bloco anterior no fluxo', suportada: true },
  { nome: 'tunnel.destination', descricao: 'O destinatário do túnel, que normalmente é a identidade da aplicação do bot. Disponível apenas para mensagens de túnel (encaminhadas por um roteador, por exemplo).', suportada: true },
  { nome: 'tunnel.identity', descricao: 'A identidade do túnel. Disponível apenas para mensagens de túnel (encaminhadas por um roteador, por exemplo).', suportada: true },
  { nome: 'tunnel.originator', descricao: 'O nodo do originador do túnel, que é o identificador do cliente no proprietário do túnel. Em um roteador, é o identificador original do cliente. Disponível apenas para mensagens de túnel (encaminhadas por um roteador, por exemplo).', suportada: true },
  { nome: 'tunnel.owner', descricao: 'A identidade do proprietário do túnel. Em um roteador, é a identidade da aplicação do roteador. Disponível apenas para mensagens de tunnel (encaminhadas por um roteador, por exemplo).', suportada: true },
] as const;
